### ISSUE TITLE
이거 왜 프로젝트 전체로 옮기면 안에있는res폴더는 인식하는ㄷ ㅔsrc 폴더인식못하지?

### ISSUE THREAD

**Issue by kmdrp** [galcyurio/Messenger_TeamProject#7]
.......왜똑같은 루트에있는 폴던데 뭐는 인식하고뭐는인식못하는지모르겠다...

그래서 일단 따로java파일만 push햇어요 근데 실수로 master branch로 push햇네요 
필요한거있으면 카톡주세요

**Comment by galcyurio** [comment]
아직 push 를 안해주셨어요.

cmd 창에서 Messenger_TeamProject 폴더까지 가신다음에

````git
git add .
git commit -m "commit message"
git push origin kmdrp
````

위 명령어를 써주세요.
하다가 안되는 부분 있으시면 카톡으로 연락주세요.
